<table width="780" border="0" align="center" cellpadding="0" cellspacing="0" background="img/body_bg.gif" > 
        <tr> 
          <td class="pads-left-right pads-top-bottom"><table width="100%"  border="0" cellspacing="0" cellpadding="0"> 
              <tr> 
                <td class="white content-box"> <p class="heading">Features</p> 
                  <ul class="content"> 
                    <li> 
                      <p>Create edit manage and publish posts </p> 
                    </li> 
                    <li> 
                      <p>Post to Future </p> 
                    </li> 
                    <li> 
                      <p>Comments and Feedbacks </p> 
                    </li> 
                    <li> 
                      <p>Multiple Blog Support </p> 
                    </li> 
                    <li> 
                      <p>Group Blogging * </p> 
                    </li> 
                    <li> 
                      <p>Archiving </p> 
                    </li> 
                    <li> 
                      <p>Permalinks Support ( <em>Permanent Links </em>) </p> 
                    </li> 
                    <li> 
                      <p>Web Syndication ( <em>RSS 1.0) </em> </p> 
                    </li> 
                    <li> 
                      <p>Great Themes ( <em>Template language based on Blogger.com </em>) </p> 
                    </li> 
                    <li> 
                      <p>Tag Support * </p> 
                    </li> 
                    <li> 
                      <p>Platform Independent solution </p> 
                    </li> 
                    <li> 
                      <p>Uses PHP and MySQL </p> 
                    </li> 
                    <li> 
                      <p>Free and Open Source </p> 
                    </li> 
                  </ul> 
                  <p class="content">(*<em>features are partially complete </em>) </p> 
                  <p><span class="heading">Future Roadmap</span></p> 
                  <ul> 
                    <li> 
                      <p class="content">Improved data validation and constraint checking </p> 
                    </li> 
                    <li> 
                      <p class="content">Better user work flows </p> 
                    </li> 
                    <li> 
                      <p class="content">Rich Text Editor </p> 
                    </li> 
                    <li> 
                      <p class="content">File and Image Upload </p> 
                    </li> 
                    <li> 
                      <p class="content">Template Migration Utility </p> 
                    </li> 
                    <li> 
                      <p class="content">Web Syndication ( <em>Atom </em>) </p> 
                    </li> 
                    <li> 
                      <p><span class="content">Comment Syndication</span></p> 
                    </li> 
                  </ul> 
                  <p class="content">&nbsp;</p></td> 
              </tr> 
            </table></td> 
        </tr> 
      </table>
