    <table width="780" border="0" align="center" cellpadding="0" cellspacing="0" background="img/body_bg.gif" >
      <tr>
        <td class="pads-left-right pads-top-bottom">
          <table width="100%"  border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td class="white content-box">
              <p class="heading">What is Qikblogger? </p>
              
              <p class="content">Qikblogger is a multi-user multi-blog engine (PHP + MySQL) with support for permalinks, tags, RSS and customised themes .</p>
              <p class="heading">Motivation </p>
              <p class="content">The motivation behind Qikblogger is to provide an ideal solution for individuals, corporates, communities, institutions, organistaions and universities interested in providing a blogging space of their own.</p>
                
              <p class="heading">Developer</p>
                <ul class="content"> 
                    <li> 
                      <p class="content">Homepage : <a class="content-links" href="http://www.akshaysurve.com" title="Qikblogger developed by Akshay Surve - Homepage">Akshay Surve's Homepage</a></p>
                    </li> 
                    <li> 
                      <p class="content">Blog: <a class="content-links" href="http://www.akshaysurve.com/blog" title="Qikblogger developed by Akshay Surve - Blog">Akshay Surve's Blog</a></p>
                    </li> 
                    <li> 
                        <p class="content">Projects: <a class="content-links" href="http://www.akshaysurve.com/projects" title="Akshay Surve - Projects">Akshay Surve's Projects</a></p>
                    </li> 
                  </ul> 
                  
              
                
            <p><span class="heading">Announcements</span></p> 
                  <ul class="content"> 
                    <li> 
                      <p><a href="http://qikblogger.sourceforge.net/" target="_blank" class="content-links">Qikblogger</a> is now hosted on <a href="http://www.sourceforge.net/" target="_blank" class="content-links">Sourceforge.net</a></p> 
                    </li> 
                    <li> 
                      <p>Pre-Alpha release would be available for download in the last week of December 2005</p> 
                    </li> 
                    <li> 
                      <p>Alpha released available for downlaod on January 2006</p> 
                    </li> 
                    <li> 
                      <p>Qikblogger release code named Krypton is now BETA. (Yup, this is BETA version)</p> 
                    </li> 
                  </ul> 
            </td>
          </tr>
          </table>
        </td>
      </tr>
    </table>
