      <table width="780" border="0" align="center" cellpadding="0" cellspacing="0" class="body-bg" > 
        <tr> 
          <td class="pads-left-right pads-top-bottom"><table width="100%"  border="0" cellspacing="0" cellpadding="0"> 
              <tr> 
                <td class="white content-box"> <p class="heading error"> 
                    <?=$critical_err_msg?> 
                  </p> 
                  <p class="content status"> 
                    <?=$status_msg?> 
                  </p></td> 
              </tr> 
            </table></td> 
        </tr> 
      </table>
