    <table width="780" border="0" align="center" cellpadding="0" cellspacing="0" class="body-bg" >
      <tr>
        <td class="pads-left-right pads-top-bottom"><table width="100%"  border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td class="white content-box">
              <p class="heading">Help</p>              
              <p class="content">We at Qikblogger appreciate your interest and enthusiasm. Presently, Qikblogger v0.9(pre-alpha) code named Krypton (<a href="http://en.wikipedia.org/wiki/Krypton_(planet)" class="links content-links" target="blank" />why?</a>) has been released. Also Qikblogger release code named Krypton is now in BETA</p>
              <p class="content">Please share you valuable feedback and encouraging comments on our blog or by mail.</p>
              
              <ul class="content">
                <li> 
                  <p><a href="http://qikblogger.sourceforge.net" target="blank" class="links content-links" />Qikblogger Sourceforge.net Homepage</a></p> 
                </li> 
                <li> 
                  <p><a href="http://qikblogger.blogspot.com" target="blank" class="links content-links" />Qikblogger Blog</a> (<a href="blogs.php?blog_name=qikblogger" target="blank" class="links content-links" />Qikblogger</a> Blog on this demo site)</p> 
                </li> 
                <li> 
                  <p><a href="mailto:ak47surve@yahoo.com" target="blank" class="links content-links" />Email</a></p> 
                </li>
                <li> 
                      <p class="content">Developer's Homepage : <a class="content-links" href="http://www.akshaysurve.com" title="Qikblogger developed by Akshay Surve - Homepage">Akshay Surve's Homepage</a></p>
                    </li> 
                    <li> 
                      <p class="content">Developer's Blog: <a class="content-links" href="http://www.akshaysurve.com/blog" title="Qikblogger developed by Akshay Surve - Blog">Akshay Surve's Blog</a></p>
                    </li> 
                    <li> 
                        <p class="content">Developer's Projects: <a class="content-links" href="http://www.akshaysurve.com/projects" title="Akshay Surve - Projects">Akshay Surve's Projects</a></p>
                    </li> 
              </ul> 
              </td>
          </tr>
        </table>
          </td>
      </tr>
    </table>
