<table width="780" border="0" align="center" cellpadding="0" cellspacing="0" background="img/body_bg.gif" > 
        <tr> 
          <td class="pads-left-right pads-top-bottom"><table width="100%"  border="0" cellspacing="0" cellpadding="0"> 
              <tr> 
                <td class="white content-box"> 
                  
                <p class="heading">Features</p> 
                  <ul class="content"> 
                    <li> 
                      <p>Multi-user Multi-blog support</p> 
                    </li> 
                    <li> 
                      <p>Custom theme support - Blogger Themes can be easily ported to QikBlogger) </p> 
                    </li> 
                    <li> 
                      <p>Web Syndication (<em>RSS 2.0</em> and <em>Atom 1.0</em>) </p> 
                    </li> 
                    <li> 
                      <p>Tagging</p> 
                    </li> 
                    <li> 
                      <p>Group Blogging </p> 
                    </li> 
                    <li> 
                      <p>Permalinks (<em>Permanent Links</em>) </p> 
                    </li> 
                    <li> 
                      <p>Comment Moderation</p> 
                    </li> 
                    <li> 
                      <p>Limited User Management</p> 
                    </li> 
                    <li> 
                      <p>Powered by PHP and MySQL</p> 
                    </li> 
                    <li> 
                      <p>Free and Open Source (released under <a href="http://mirror.opensource.dk/licenses/gpl-license.php" target="_blank" class="content-links">GNU General Public License</a>) </p> 
                    </li> 
                  </ul> 

                <p class="content">&nbsp;</p>
                <p class="heading">Featured Blogs</p> 
                  <ul class="content"> 
                    <li> 
                      <p><a href="blogs.php?blog_name=qikblogger" target="_blank" class="content-links">Qikblogger</a> </p> 
                    </li> 
                    <li> 
                      <p><a href="blogs.php?blog_name=research" target="_blank" class="content-links">Research</a> </p> 
                    </li> 
                    <li> 
                      <p><a href="blogs.php?blog_name=barbie" target="_blank" class="content-links">Barbie</a> </p> 
                    </li> 
                    <li> 
                      <p>Offcourse!!! you are welcome to start your own.</p> 
                    </li> 
                  </ul> 
                      <p class="content">&nbsp;</p>

                <p><span class="heading">Future Roadmap</span></p> 
                  <ul> 
                    <li> 
                      <p class="content">Improved data validation and constraint checking </p> 
                    </li> 
                    <li> 
                      <p class="content">Rich Text Editor </p> 
                    </li> 
                    <li> 
                      <p class="content">File and Image Upload </p> 
                    </li> 
                    <li> 
                      <p class="content">Template Migration Utility </p> 
                    </li> 
                    <li> 
                      <p><span class="content">Comment Syndication</span></p> 
                    </li> 
                  </ul> 

                <p class="content">&nbsp;</p>
                
                
                
                
                
                </td> 
              </tr> 
            </table></td> 
        </tr> 
      </table>
