      <table width="780" border="0" align="center" cellpadding="0" cellspacing="0" class="body-bg"> 
        <tr> 
          <td class="pads-left-right pads-bottom"><table width="100%"  border="0" cellspacing="0" cellpadding="0"> 
              <tr> 
                <td><a href="index.php" class="links footer-links">Home</a> <span class="content">|</span> <a href="about.php"  class="links footer-links">About</a> <span class="content">|</span> <a href="browse.php" class="links footer-links">Browse</a> <span class="content">|</span> <a href="features.php" class="links footer-links">Features</a> <span class="content">|</span> <a href="help.php" class="links footer-links">Help</a><span class="content"> | </span>
                  <span class="content">Copyright &copy;2006 <a href="http://www.akshaysurve.com" target="_blank" class="content-links">Akshay Surve</a>. Released under  <a href="http://mirror.opensource.dk/licenses/gpl-license.php" target="_blank" class="content-links">GNU GPL</a></span></td> 
              </tr> 
            </table></td> 
        </tr> 
      </table>
