                  <table width="100%"  border="0" cellspacing="0" cellpadding="0"> 
                    <tr class="main-menu"> 
                      <td width="14%"><a href="<?=WEB_ROOT?>/posts.php?blog_name=<?=$b->blog_name?>" class="main-menu selected">Posting</a></td> 
                      <td width="14%">&nbsp;</td> 
                      <td width="14%">&nbsp;</td> 
                      <td width="58%"><a href="<?=WEB_ROOT?>/blogs.php?blog_name=<?=$b->blog_name?>" target="_blank" class="main-menu">View Blog</a></td> 
                    </tr> 
                  </table>
                  <table width="100%"  border="0" cellpadding="0" cellspacing="0"> 
                    <tr> 
                      <td width="14%" class="sub-menu"><a href="<?=WEB_ROOT?>/post-create.php?blog_name=<?=$b->blog_name?>" class="sub-menu selected">Create</a></td> 
                      <td width="14%" class="sub-menu"><a href="<?=WEB_ROOT?>/posts.php?blog_name=<?=$b->blog_name?>" class="sub-menu">Edit</a></td> 
                      <td width="72%" class="sub-menu">&nbsp;</td> 
                    </tr> 
                  </table>
