                  <table width="100%"  border="0" cellspacing="0" cellpadding="0"> 
                    <tr class="main-menu"> 
                      <td width="14%"><a href="<?=WEB_ROOT?>/posts.php?blog_name=<?=$b->blog_name?>" class="main-menu">Posting</a></td> 
                      <td width="14%"><a href="<?=WEB_ROOT?>/blog-options-basic.php?blog_name=<?=$b->blog_name?>" class="main-menu">Settings</a></td> 
                      <td width="14%"><a href="<?=WEB_ROOT?>/template-edit.php?blog_name=<?=$b->blog_name?>" class="main-menu selected">Template</a></td> 
                      <td width="58%"><a href="<?=WEB_ROOT?>/blogs.php?blog_name=<?=$b->blog_name?>" target="_blank" class="main-menu">View Blog</a></td> 
                    </tr> 
                  </table>
                  <table width="100%"  border="0" cellpadding="0" cellspacing="0"> 
                    <tr> 
                      <td width="20%" class="sub-menu"><a href="<?=WEB_ROOT?>/template-edit.php?blog_name=<?=$b->blog_name?>" class="sub-menu selected">Edit Current</a></td> 
                      <td width="20%" class="sub-menu"><a href="<?=WEB_ROOT?>/template-choose.php?blog_name=<?=$b->blog_name?>" class="sub-menu">Pick New</a></td> 
                      <td width="60%" class="sub-menu">&nbsp;</td> 
                    </tr> 
                  </table>
