<table width="100%" height="100" border="0" cellpadding="0" cellspacing="0" class="head-sides-bg"> 
  <tr> 
    <td><table width="780" height="100" border="0" align="center" cellpadding="0" cellspacing="0" class="head-bg"> 
        <tr> 
          <td class="pads-left-right"><div class="logo" id="logo"><a href="index.php" title="Qikblogger Home" /><img  border="0" src="img/logo_final.gif" width="150" height="44" /></a></div></td>
          <td />
            <div class="content pads-left-right" align="right" style="color:#FFFFFF;font-weight:normal;">Signed in as: <span style="color:#FFFFFF;font-weight:bold;"><?=$u->username?></span></div>
            <div class="content pads-left-right" align="right"><a class="sign-out" href="logout.php" />Sign out</a></div></td>
        </tr> 
      </table></td> 
  </tr> 
</table>
<table width="100%"  border="0" cellpadding="0" cellspacing="0" class="center-sides-bg-g"> 
  <tr> 
    <td ><table width="780" height="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="center-bg-g"> 
        <tr> 
          <td height="2" ><img src="img/spacer.gif" width="2" height="4" /></td> 
        </tr> 
      </table></td> 
  </tr> 
</table>
