<table width="100%"  border="0" cellpadding="0" cellspacing="0" class="center-sides-bg-g"> 
  <tr> 
    <td ><table width="780" height="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="center-bg-g"> 
        <tr> 
          <td height="2" ><img src="img/spacer.gif" width="2" height="4" /></td> 
        </tr> 
      </table></td> 
  </tr> 
</table>
<table width="100%" height="2" border="0" cellpadding="0" cellspacing="0" class="head-sides-bg"> 
  <tr> 
    <td>&nbsp;</td> 
  </tr> 
</table>

